version: 2
jobs:
  build:
    machine: true
    working_directory: ~/quadlek
    steps:
      - checkout
      - run:
          name: Build and deploy container
          command: |
            TAG=$CIRCLE_BRANCH
            docker build -t quay.io/dosilek/quadlek:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
            docker push quay.io/dosilek/quadlek:$TAG
            if [[ $CIRCLE_BRANCH == "master" ]]; then ssh circleci@quadlek.jirw.in 'sudo systemctl restart quadlek'; fi